name: Jupyter
env:
  SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}

on:
  workflow_dispatch:  # Allows manual execution
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - id: repo 
        name: Repo Checkout
        uses: actions/checkout@v3  # Updated to latest version
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  # Ensures correct authentication

      - id: python
        name: Python Setup & Packages Installation
        uses: actions/setup-python@v4  # Updated to v4
        with:
          python-version: '3.9'
          cache: 'pip'

      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install jupyter nbconvert  # Ensure Jupyter & nbconvert are installed

      - id: jupyter 
        name: Jupyter Notebook Execution
        run: |
          jupyter nbconvert --execute --to notebook --output download-output.ipynb download.ipynb
        shell: bash 

      - id: commit
        name: Commit files
        run: |
          git config --local user.name "github-actions"
          git config --local user.email "actions@github.com"
          git add .
          git commit -m "GH ACTION Headlines $(date)" || echo "No changes to commit"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Authentication handled automatically
