name: Jupyter

on:
  workflow_dispatch:  # Allows manual execution
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - id: repo 
        name: Repo Checkout
        uses: actions/checkout@v2

      - id: python
        name: Python Setup & Packages Installation
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          cache: 'pip'
      - run: pip install -r requirements.txt

      - id: jupyter 
        name: Jupyter Notebook Execution
        run: |
          pip install jupyter nbconvert  # Ensure Jupyter is installed
          jupyter nbconvert --execute --to notebook --output download-output.ipynb download.ipynb
        shell: bash 

      - id: commit
        name: Commit files
        run: |
          git config --local user.name "github-actions"
          git config --local user.email "actions@github.com"
          git add .
          git commit -m "GH ACTION Headlines $(date)" || echo "No changes to commit"
          git push origin main
        env:
          REPO_KEY: ${{ secrets.GITHUB_TOKEN }}
          username: github-actions
